/**
 * generated by Xtext
 */
package visualizationDesignLanguage.DSL.serializer;

import visualizationDesignLanguage.DSL.serializer.AbstractVDSemanticSequencer;

@SuppressWarnings("all")
public class VDSemanticSequencer extends AbstractVDSemanticSequencer {
}
