/**
 * generated by Xtext
 */
package visualizationDesignLanguage.DSL.serializer;

import visualizationDesignLanguage.DSL.serializer.AbstractVDSyntacticSequencer;

@SuppressWarnings("all")
public class VDSyntacticSequencer extends AbstractVDSyntacticSequencer {
}
