/**
 * generated by Xtext
 */
package visualizationDesignLanguage.DSL.validation;

import visualizationDesignLanguage.DSL.validation.AbstractVDValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class VDValidator extends AbstractVDValidator {
}
