/*
* generated by Xtext
*/
package visualizationDesignLanguage.DSL.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VDAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("visualizationDesignLanguage/DSL/parser/antlr/internal/InternalVD.tokens");
	}
}
