/*
* generated by Xtext
*/
package visualizationDesignLanguage.DSL.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import visualizationDesignLanguage.DSL.services.VDGrammarAccess;

public class VDParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VDGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected visualizationDesignLanguage.DSL.parser.antlr.internal.InternalVDParser createParser(XtextTokenStream stream) {
		return new visualizationDesignLanguage.DSL.parser.antlr.internal.InternalVDParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Dashboard";
	}
	
	public VDGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VDGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
