/*
 * generated by Xtext
 */
package visualizationDesignLanguage.DSL.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractVDValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("fr.uns.i3s.sparks.modalis.israfel.visualisationdesignlanguage"));
		return result;
	}
}
